-- CREATE DATABASE 'TRAINING'
DECLARE @NEW_DATABASE_NAME CHAR(50);
SET @NEW_DATABASE_NAME = 'TRAINING';

IF NOT EXISTS 
	(SELECT NAME
	FROM SYS.DATABASES
	WHERE NAME = @NEW_DATABASE_NAME)
BEGIN
	CREATE DATABASE TRAINING
END;

-- CREATE TABLE 'CRIME'
USE TRAINING;

IF NOT EXISTS (
	SELECT NAME
	FROM SYS.TABLES
	WHERE PARENT_OBJECT_ID != (
	SELECT DATABASE_ID
	FROM SYS.DATABASES
	WHERE NAME LIKE 'TRAINING')
	AND NAME = 'CRIME')

BEGIN
	CREATE TABLE CRIME (
		DR_NO INT,
		DATE_RPTD DATETIME,
		DATE_OCC DATETIME,
		TIME_OCC SMALLINT,
		AREA SMALLINT,
		AREA_NAME VARCHAR(100),
		RPT_DIST_NO SMALLINT,
		PART_1_2 SMALLINT,
		CRM_CD SMALLINT,
		CRM_CD_DESC VARCHAR(100),
		MOCODES VARCHAR(100),
		VICT_AGE SMALLINT,
		VICT_SEX CHAR(1),
		PREMIS_CD SMALLINT,
		PREMIS_DESC NVARCHAR(100),

		WEAPON_DESC VARCHAR(100),
		STATUS_DESC VARCHAR(100),
		CRM_CD_1 SMALLINT,
		CRM_CD_2 SMALLINT,
		CRM_CD_3 SMALLINT,
		CRM_CD_4 SMALLINT,
		"LOCATION" VARCHAR(100),
		CROSS_STREET VARCHAR(100),
		LAT FLOAT,
		LON FLOAT,)
END;

-- IMPORT FLAT FILE TO TABLE 'CRIME'
BULK INSERT dbo.CRIME
FROM '..crime-sql-pandas-pyspark/data/data-raw.csv'
WITH(
	FORMAT = 'CSV',
	FIRSTROW = 2,
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIELDQUOTE = '"'
);

/*
(1005104 rows affected)

Completion time: 2025-08-08T12:37:58.0242063-04:00
*/



