USE TRAINING;

-- CRIME TRENDS & VOLUME.
/* What are the most frequently reported crime types (CRM_CD_DESC) overall?						*/
WITH BASE AS (
	SELECT 
		CRM_CD, CRM_CD_DESC,
		COUNT(*) AS TOTAL,
		RANK()	OVER(ORDER BY COUNT(*) DESC) AS RANKING
	FROM 
		CRIME
	GROUP BY 
		CRM_CD, CRM_CD_DESC
)
SELECT *
FROM BASE
WHERE RANKING = 1;

/* How many crimes were reported each month? Show a trend over time.							*/
WITH BASE AS (
	SELECT 
		--*,
		COUNT(*) AS TOTAL,
		YEAR(DATE_OCC) AS 'YEAR',
		MONTH(DATE_OCC) AS 'MONTH'
	FROM CRIME
	GROUP BY 
		YEAR(DATE_OCC),
		MONTH(DATE_OCC))

SELECT *
FROM BASE
ORDER BY 'YEAR', 'MONTH';

/* Which day of the week has the highest crime occurrences?										*/
SELECT 
	RANK() OVER(ORDER BY COUNT(*) DESC) AS RANKING,
	CASE 
		WHEN DATEPART(WEEKDAY, DATE_OCC) = 1 THEN 'MONDAY'
		WHEN DATEPART(WEEKDAY, DATE_OCC) = 2 THEN 'TUESDAY'
		WHEN DATEPART(WEEKDAY, DATE_OCC) = 3 THEN 'WEDNESDAY'
		WHEN DATEPART(WEEKDAY, DATE_OCC) = 4 THEN 'THURSDAY'
		WHEN DATEPART(WEEKDAY, DATE_OCC) = 5 THEN 'FRIDAY'
		WHEN DATEPART(WEEKDAY, DATE_OCC) = 6 THEN 'SATURDAY'
		WHEN DATEPART(WEEKDAY, DATE_OCC) = 7 THEN 'SUNDAY'
	END AS WEEK_DAY,
	COUNT(*) AS TOTAL
FROM CRIME
GROUP BY DATEPART(WEEKDAY, DATE_OCC);

/* What is the average number of crimes per area (AREA_NAME) per month?							*/
WITH BASE AS (
SELECT
	AREA_NAME,
	YEAR(DATE_OCC) AS CAL_YEAR,
	MONTH(DATE_OCC) AS CAL_MONTH,
	COUNT(*) AS MONTH_TOTAL
FROM CRIME
GROUP BY 
	AREA_NAME,
	YEAR(DATE_OCC),
	MONTH(DATE_OCC)
)
SELECT 
	AREA_NAME,
	AVG(MONTH_TOTAL) AS AVG_MONTHLY_CRIMES
FROM
	BASE
GROUP BY 
	AREA_NAME
ORDER BY 2 DESC;

/* How has crime volume changed year over year?													*/
SELECT 
	YEAR(DATE_OCC) AS 'YEAR',
	COUNT(*) AS CRIME_TOTAL,
	ISNULL(COUNT(*) - LAG(COUNT(*), 1) OVER(ORDER BY YEAR(DATE_OCC)), 0) AS CHANGE_YOY,
	COUNT(DISTINCT MONTH(DATE_OCC)) AS MONTHS_REPORTED
FROM CRIME
GROUP BY YEAR(DATE_OCC);

-- LOCATION BASED INSIGHTS.
/* Which AREA_NAME reports the highest number of violent crimes (e.g., crimes with weapons)?	*/
WITH VIOLENT_CODES AS (
	SELECT 
		CODE FROM (VALUES 
			(900), (930), (625), (940), (810), (113), (236), (910), (231),
			(926), (648), (121), (110), (250), (922), (230), (820), (760),
			(220), (812), (623), (822), (434), (763), (920), (840), (624), 
			(815), (806), (627), (436), (942), (830), (761), (122), (901), 
			(647), (821), (622), (626), (437), (921), (753), (435), (210), 
			(251), (235), (860), (755)) V(CODE)
),
BASE AS (
	SELECT
		COUNT(*) AS OCCURRENCE,
		AREA_NAME
	FROM CRIME
	WHERE CRM_CD IN (SELECT CODE FROM VIOLENT_CODES)
	GROUP BY AREA_NAME
),
RANKED AS (
	SELECT
		AREA_NAME,
		OCCURRENCE, 
		DENSE_RANK() OVER(ORDER BY OCCURRENCE DESC) AS RANK 
	FROM BASE
)
SELECT * FROM RANKED WHERE [RANK] = 1;

/* What is the most common type of crime in each reporting district (RPT_DIST_NO)?				*/
WITH BASE AS (
	SELECT 
		RPT_DIST_NO,
		CRM_CD,
		CRM_CD_DESC,
			COUNT(CRM_CD) 
		AS TOTAL,
			DENSE_RANK() OVER(
			PARTITION BY RPT_DIST_NO 
			ORDER BY COUNT(CRM_CD) DESC) 
		AS OCCR_RNK
	FROM CRIME
	GROUP BY 
		RPT_DIST_NO, 
		CRM_CD,
		CRM_CD_DESC
)
SELECT * FROM BASE WHERE OCCR_RNK IN (1) ORDER BY RPT_DIST_NO;

/* What are the top 5 locations (LOCATION) with the highest crime occurrences?					*/
SELECT 
	[LOCATION]
		,COUNT(*) AS TOTAL
		,ROW_NUMBER() OVER (ORDER BY(SELECT NULL)) AS RANK  
FROM CRIME
GROUP BY [LOCATION]
ORDER BY COUNT(*) DESC
OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY;

/* Are there any significant crime clusters by latitude/longitude (LAT, LON)?					*/
SELECT 
	AREA_NAME,
	ROUND(LAT, 2) AS LAT_1KM_GROUP,
	ROUND(LON, 2) AS LON_1KM_GROUP,
	COUNT(*) AS CRIME_COUNT
FROM CRIME
WHERE 
	LAT IS NOT NULL
	AND LON IS NOT NULL
GROUP BY
	AREA_NAME,
	ROUND(LAT, 2),
	ROUND(LON, 2)
ORDER BY COUNT(*) DESC
OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY;

-- TIME OF CRIME ANALYSIS.
/* At what times of day (TIME_OCC) are crimes most commonly reported?							*/
WITH BASE AS ( 
SELECT 
		COUNT(*) AS
	TOTAL,
	CASE 
	WHEN TIME_OCC BETWEEN 0 AND 559 THEN 'NIGHT'
	WHEN TIME_OCC BETWEEN 600 AND 1159 THEN 'MORNING'
	WHEN TIME_OCC BETWEEN 1200 AND 1759 THEN 'NOON'
	WHEN TIME_OCC BETWEEN 1800 AND 2359 THEN 'EVENING' 
	END AS TOD
FROM CRIME
GROUP BY 
	CASE 
	WHEN TIME_OCC BETWEEN 0 AND 559 THEN 'NIGHT'
	WHEN TIME_OCC BETWEEN 600 AND 1159 THEN 'MORNING'
	WHEN TIME_OCC BETWEEN 1200 AND 1759 THEN 'NOON'
	WHEN TIME_OCC BETWEEN 1800 AND 2359 THEN 'EVENING' 
	END
),
TIMEFRAMES AS (
	SELECT 'NIGHT' AS TOD, '0000-0559' AS TIMEFRAME
	UNION ALL
	SELECT 'MORNING' AS TOD, '0600-1159' AS TIMEFRAME
	UNION ALL
	SELECT 'NOON' AS TOD, '1200-1759' AS TIMEFRAME
	UNION ALL
	SELECT 'EVENING' AS TOD, '1800-2359' AS TIMEFRAME
)
SELECT
	B.TOD,
	B.TOTAL CRIME_TOTAL,
	T.TIMEFRAME
FROM
	BASE B
	JOIN TIMEFRAMES T ON B.TOD = T.TOD
ORDER BY B.TOTAL DESC;

/* Are there specific hours where certain crime types spike?									*/
WITH BASE2 AS (
    SELECT 
        BASE.HR 
		,COUNT(*) AS CUR_HR_TOTAL
		,LAG(COUNT(*)) OVER(ORDER BY BASE.HR ASC) AS PREV_HR_TOTAL
		,COUNT(*) - LAG(COUNT(*)) OVER(ORDER BY BASE.HR ASC) AS DIFF_CUR_PREV_HR
		,IIF(BASE.HR = 0 , 0, BASE.HR - 100) AS PREV_HR
    FROM (
        SELECT 
            TIME_OCC,
			CASE 
			WHEN TIME_OCC > 59 THEN FLOOR(TIME_OCC / 100) * 100
			ELSE 0 
			END AS HR
        FROM CRIME
    ) BASE
    GROUP BY BASE.HR
)
SELECT TOP 5
    HR,
    CUR_HR_TOTAL,
    PREV_HR,
    PREV_HR_TOTAL,
    DIFF_CUR_PREV_HR,
    RANK() OVER(ORDER BY DIFF_CUR_PREV_HR DESC) AS RNK
 FROM BASE2 ORDER BY [DIFF_CUR_PREV_HR] DESC;
